apiVersion: v1
kind: Service
metadata:
  name: rails-service
  namespace: healthcare
spec:
  selector:
    app: rails-web
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30000
